service: myWallet
frameworkVersion: "2"
provider:
  name: aws
  region: eu-south-1
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
functions:
  getAllUsers:
    handler: app.getAllUsers
    events:
      - http:
          path: /users/getAllUsers
          method: GET
          cors: true
  getUserById:
    handler: app.getUserById
    events:
      - http:
          path: /users/getUserById/{id}
          method: GET
          cors: true
  createUser:
    handler: app.createUser
    events:
      - http:
          path: /users/addUser
          method: POST
          cors: true
  updateUser:
    handler: app.updateUser
    events:
      - http:
          path: /users/updateUser/{id}
          method: PATCH
          cors: true
  deleteUser:
    handler: app.deleteUser
    events: 
      - http:
          path: /users/deleteUser/{id}
          method: DELETE
          cors: true
  getAllCategories:
    handler: app.getAllCategories
    events: 
      - http:
          path: /category/
          method: GET
          cors: true
  getCategoryFromId:
    handler: app.getCategoryFromId
    events:
      - http:
          path: /category/{id}
          method: GET
          cors: true
  deleteCategory:
    handler: app.deleteCategory
    events:
      - http:
          path: /category/deleteCategory/{id}
          method: DELETE
          cors: true
  getAllEvents:
    handler: app.getAllEvents
    events:
      - http:
          path: /events/
          method: GET
          cors: true
  getEventById:
    handler: app.getEventById
    events:
      - http:
          path: /events/{id}
          method: GET
          cors: true
  getEventbyUser:
    handler: app.getEventbyUser
    events:
      - http:
          path: /events/getEventByUser/{id}
          method: GET
          cors: true
  getEventsByuserCategory:
    handler: app.getEventsByUserCategory
    events:
      - http:
          path: /events/getEventByUser/{id}/{categoryId}
          method: GET
          cors: true
  getAllDeposit:
    handler: app.getAllDeposit
    events:
      - http:
          path: /events/getDeposits/{id}
          method: GET
          cors: true
  getAllWithdraws:
    handler: app.getAllWithdraws
    events:
      - http:
          path: /events/getAllWithdraws/{id}
          method: GET
          cors: true
  createEvent:
    handler: app.createEvent
    events:
      - http:
          path: /events/createEvent/{userId}/{categoryId}
          method: POST
          cors: true